resources:
  - ../../base
  - namespace.yaml
  - configmap-db.yaml
  - ingress-hosts.yaml

namespace: capstone-backend

nameSuffix: -steven

replicas:
  - name: backend-a
    count: 3
  - name: backend-b
    count: 3

images:
  - name: backend-a
    newName: acrcapstoneproda1b2c.azurecr.io/backend-a
    newTag: "144"
  - name: backend-b
    newName: acrcapstoneproda1b2c.azurecr.io/backend-b
    newTag: "144"

replacements:
- source:
    kind: ConfigMap
    name: ingress-hosts
    fieldPath: data.BACKEND_A_HOST
  targets:
  - select:
      kind: Ingress
      name: backend-a-ingress
    fieldPaths:
    - spec.rules.0.host
- source:
    kind: ConfigMap
    name: ingress-hosts
    fieldPath: data.BACKEND_B_HOST
  targets:
  - select:
      kind: Ingress
      name: backend-b-ingress
    fieldPaths:
    - spec.rules.0.host