apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-b-ingress
  namespace: capstone-backend
spec:
  ingressClassName: nginx
  rules:
  - host: placeholder
    http:
      paths:
      - path: /api/b
        pathType: Prefix
        backend:
          service:
            name: backend-b
            port:
              number: 80
