resources:
  - backend-a-deployment.yaml
  - backend-a-service.yaml
  - backend-a-hpa.yaml
  - backend-a-ingress.yaml
  - backend-b-deployment.yaml
  - backend-b-service.yaml
  - backend-b-hpa.yaml
  - backend-b-ingress.yaml
  - ingress-hosts.yaml
  - postgres-secret.yaml