apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  DB_HOST: appdb.postgres.database.azure.com
  DB_PORT: "5432"
  DB_NAME: appdb
  DB_USER: stevushka@appdb

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-hosts
data:
  BACKEND_A_HOST: backend-a.qa.capstone.com
  BACKEND_B_HOST: backend-b.qa.capstone.com