resources:
  - ../../base
  - namespace.yaml
  - configmap-db.yaml

namespace: capstone-backend

nameSuffix: -steven

replicas:
  - name: backend-a
    count: 2
  - name: backend-b
    count: 2

images:
  - name: backend-a
    newName: acrcapstoneqaa1b2c.azurecr.io/backend-a
    newTag: "144"
  - name: backend-b
    newName: acrcapstoneqaa1b2c.azurecr.io/backend-b
    newTag: "144"

configMapGenerator:
- name: ingress-hosts
  behavior: merge
  literals:
  - BACKEND_A_HOST=backend-a.qa.capstone.com
  - BACKEND_B_HOST=backend-b.qa.capstone.com